// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService handles application-level operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * CreateSymlink creates a symlink for the vaul command in the user's PATH
 * Returns a message indicating success or failure
 * @returns {$CancellablePromise<string>}
 */
export function CreateSymlink() {
    return $Call.ByID(1206422185);
}

/**
 * Quit quits the application
 * @returns {$CancellablePromise<void>}
 */
export function Quit() {
    return $Call.ByID(2719743713);
}

/**
 * SetApp sets the application reference
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(3487267257, app);
}

/**
 * SymlinkExists checks if the vaul symlink already exists
 * Returns true if the symlink exists and points to the current executable
 * @returns {$CancellablePromise<boolean>}
 */
export function SymlinkExists() {
    return $Call.ByID(1072975037);
}
