// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CommandService handles storing and retrieving commands
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddCommand adds a new command to storage
 * @param {string} content
 * @returns {$CancellablePromise<$models.Command>}
 */
export function AddCommand(content) {
    return $Call.ByID(3452678840, content).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * AddCommandWithCategory adds a new command with a category to storage
 * @param {string} content
 * @param {string} category
 * @returns {$CancellablePromise<$models.Command>}
 */
export function AddCommandWithCategory(content, category) {
    return $Call.ByID(457148008, content, category).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * AddCommandWithCategoryAndAlias adds a new command with category and alias
 * @param {string} content
 * @param {string} category
 * @param {string} alias
 * @returns {$CancellablePromise<$models.Command>}
 */
export function AddCommandWithCategoryAndAlias(content, category, alias) {
    return $Call.ByID(2795166819, content, category, alias).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CreateCategory creates a new category
 * @param {string} name
 * @param {string} color
 * @returns {$CancellablePromise<$models.Category>}
 */
export function CreateCategory(name, color) {
    return $Call.ByID(3920645540, name, color).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DeleteCategory deletes a category and optionally reassigns its commands
 * @param {string} id
 * @param {string} reassignToCategory
 * @returns {$CancellablePromise<void>}
 */
export function DeleteCategory(id, reassignToCategory) {
    return $Call.ByID(2228038743, id, reassignToCategory);
}

/**
 * DeleteCommand removes a command by ID
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteCommand(id) {
    return $Call.ByID(1888656992, id);
}

/**
 * GetCategories returns all categories
 * @returns {$CancellablePromise<$models.Category[]>}
 */
export function GetCategories() {
    return $Call.ByID(1124386808).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetCommandByAlias retrieves a command by its alias
 * @param {string} alias
 * @returns {$CancellablePromise<$models.Command>}
 */
export function GetCommandByAlias(alias) {
    return $Call.ByID(607494344, alias).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetCommands returns all stored commands
 * @returns {$CancellablePromise<$models.Command[]>}
 */
export function GetCommands() {
    return $Call.ByID(2230805162).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetCommandsByCategory returns commands filtered by category (empty string = uncategorized)
 * @param {string} categoryID
 * @returns {$CancellablePromise<$models.Command[]>}
 */
export function GetCommandsByCategory(categoryID) {
    return $Call.ByID(3544855671, categoryID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * MergeCategories merges two categories, moving all commands from source to target
 * @param {string} sourceID
 * @param {string} targetID
 * @returns {$CancellablePromise<void>}
 */
export function MergeCategories(sourceID, targetID) {
    return $Call.ByID(3464509544, sourceID, targetID);
}

/**
 * SetUpdateCallback sets a callback function to be called when commands are updated
 * @param {$models.UpdateCallback} callback
 * @returns {$CancellablePromise<void>}
 */
export function SetUpdateCallback(callback) {
    return $Call.ByID(2519273722, callback);
}

/**
 * UpdateCategory updates an existing category
 * @param {string} id
 * @param {string} name
 * @param {string} color
 * @returns {$CancellablePromise<void>}
 */
export function UpdateCategory(id, name, color) {
    return $Call.ByID(871939973, id, name, color);
}

/**
 * UpdateCommand updates an existing command's content, category, and alias
 * @param {string} id
 * @param {string} content
 * @param {string} category
 * @param {string} alias
 * @returns {$CancellablePromise<void>}
 */
export function UpdateCommand(id, content, category, alias) {
    return $Call.ByID(2942553414, id, content, category, alias);
}

/**
 * UpdateCommandCategory updates the category of an existing command
 * @param {string} id
 * @param {string} category
 * @returns {$CancellablePromise<void>}
 */
export function UpdateCommandCategory(id, category) {
    return $Call.ByID(3448040414, id, category);
}

/**
 * ValidateAlias checks if an alias is unique (excluding the given command ID)
 * @param {string} alias
 * @param {string} excludeID
 * @returns {$CancellablePromise<boolean>}
 */
export function ValidateAlias(alias, excludeID) {
    return $Call.ByID(3019002602, alias, excludeID);
}

// Private type creation functions
const $$createType0 = $models.Command.createFrom;
const $$createType1 = $models.Category.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($$createType0);
